# Generated by Django 2.2.10 on 2023-09-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=40, verbose_name='Product name')),
                ('product_id', models.FloatField(db_index=True, verbose_name='Product ID')),
                ('product_des1', models.CharField(db_index=True, max_length=40, null=True, verbose_name='Product Descriptions 1')),
                ('product_des2', models.CharField(db_index=True, max_length=40, null=True, verbose_name='Product Descriptions 2')),
                ('product_des3', models.CharField(db_index=True, max_length=40, null=True, verbose_name='Product Descriptions 3')),
                ('product_des4', models.CharField(db_index=True, max_length=40, null=True, verbose_name='Product Descriptions 4')),
                ('product_des5', models.CharField(db_index=True, max_length=40, null=True, verbose_name='Product Descriptions 5')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_time', models.DateTimeField(db_index=True, verbose_name='creation On')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='modified On')),
            ],
            options={
                'verbose_name': 'sale',
                'verbose_name_plural': 'sales',
            },
        ),
    ]
