# Generated by Django 4.2.5 on 2023-09-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sale_product_url_alter_sale_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=40, verbose_name='Product name')),
                ('product_id', models.FloatField(db_index=True, verbose_name='Product ID')),
                ('product_des1', models.CharField(db_index=True, max_length=40, null=True, verbose_name='Product Descriptions 1')),
                ('product_category', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=30)),
                ('product_url', models.URLField(blank=True, db_index=True, null=True)),
                ('created_time', models.DateTimeField(db_index=True, verbose_name='creation On')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='modified On')),
            ],
            options={
                'verbose_name': 'sale',
                'verbose_name_plural': 'sales',
            },
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
