# Generated by Django 4.2.5 on 2023-09-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_products_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='product_category',
            field=models.CharField(choices=[('all', 'All'), ('other-category-1', 'Other Category 1'), ('other-category-1', 'Other Categoty 2'), ('other-category-1', 'Other Categoty 3')], default='All', max_length=30),
        ),
    ]
