# Generated by Django 4.2.5 on 2023-09-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.CharField(choices=[('All', 'all'), ('Other Category 1', 'other-category-1'), ('Other Category 2', 'other-category-2'), ('Other Category 3', 'other-category-3')], default='All', max_length=30),
        ),
    ]
