# Generated by Django 4.2.5 on 2023-09-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_products_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_url',
            field=models.URLField(blank=True, db_index=True, default='https://i.hizliresim.com/b70cygu.jpg', null=True),
        ),
    ]
