# Generated by Django 4.2.5 on 2023-09-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_products_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='default_tag',
            field=models.CharField(default='all_tag', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='product_category',
            field=models.CharField(choices=[('All', 'all'), ('Other Category 1', 'other-category-1'), ('Other Category 2', 'other-category-2'), ('Other Category 3', 'other-category-3'), ('Other Category 4', 'other-category-4'), ('Other Category 5', 'other-category-5'), ('Other Category 6', 'other-category-6')], default='All', max_length=30),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.CharField(choices=[('All', 'all'), ('Other Category 1', 'other-category-1'), ('Other Category 2', 'other-category-2'), ('Other Category 3', 'other-category-3'), ('Other Category 4', 'other-category-4'), ('Other Category 5', 'other-category-5'), ('Other Category 6', 'other-category-6')], default='All', max_length=30),
        ),
    ]
